language: cpp
compiler:
  - gcc

os:
  - linux

addons:
  apt:
    packages:
      - cmake

script:
  - mkdir build &&  cd build
  - cmake ..
  - cmake --build . -- -j4
  - cd test
  - ctest . -C Debug -V

after_script:
  - curl -s https://raw.githubusercontent.com/report-ci/scripts/master/upload.py > upload.py
  - python upload.py --framework criterion
  - python upload.py --framework cmocka
  - python upload.py --framework unity --include */unity_test.log